# Generated by Django 6.0 on 2025-12-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreTripTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('helpful_link', models.CharField(blank=True, max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
