# Generated by Django 6.0 on 2025-12-10 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prechecklist_app', '0001_initial'),
        ('trips_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretriptask',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='trips_app.trip'),
        ),
    ]
